# Generated by Django 3.0.5 on 2020-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_event',
            name='status',
            field=models.CharField(default='invited', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='status',
            field=models.CharField(default='invited', max_length=20),
            preserve_default=False,
        ),
    ]
