# Generated by Django 3.0.5 on 2020-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='invited', max_length=20),
            preserve_default=False,
        ),
    ]
