# Generated by Django 3.0.5 on 2020-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0005_cal_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal_share',
            name='status',
            field=models.CharField(default='not viewed', max_length=20),
            preserve_default=False,
        ),
    ]
