# Generated by Django 3.0.5 on 2020-06-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0006_cal_share_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repetition_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='repetition_type',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='repetition_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='repetition_type',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
