# Generated by Django 3.0.5 on 2020-06-20 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0007_auto_20200618_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='until_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_minutes',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='until_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
