# Generated by Django 3.0.5 on 2020-06-30 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0011_auto_20200627_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='begin_datetime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='task',
            name='exception',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='exception_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarApp.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarApp.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
