# Generated by Django 3.0.5 on 2020-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0012_auto_20200629_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='until_date',
            field=models.DateField(default=None),
        ),
    ]
