# Generated by Django 3.0.5 on 2020-07-07 22:00

import CalendarApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0014_auto_20200707_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_datetime',
            field=models.DateTimeField(default=CalendarApp.models.get_aware_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(default=CalendarApp.models.get_aware_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='from_date',
            field=models.DateField(default=CalendarApp.models.get_aware_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='until_date',
            field=models.DateField(default=CalendarApp.models.get_aware_now),
        ),
    ]
